---

# common tasks for all of OSes
- name: Create filebeat group {{ filebeat_group }}
  group:
    name: '{{ filebeat_group }}'
  when: filebeat_create_user and filebeat_group != 'root'

- name: Create filebeat user {{ filebeat_user }}
  user:
    name: '{{ filebeat_user }}'
    shell: /bin/true
    create_home: false
    home: /dev/null
    comment: User for filebeat
    group: '{{ filebeat_group }}'
  when: filebeat_create_user and filebeat_user != 'root'

- include: install/Debian.yml
  when: ansible_os_family == 'Debian'

- include: install/RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: install/Solaris.yml
  when: ansible_os_family == 'Solaris'

# vi:ts=2:sw=2:et:ft=yaml
