---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: always

- include: install.yml
  tags: filebeat_install

- include: config.yml
  tags: filebeat_config
  when: filebeat_config_enabled

- include: template.yml
  tags: filebeat_template

- name: Ensure Filebeat is enabled and started at boot
  service:
    name: filebeat
    enabled: yes
    state: started
  when: filebeat_start_at_boot

# we need to disable Filebeat at boot on certain cases, such as Filebeat managed by Graylog Sidecar
- name: Ensure Filebeat is DISABLED and stopped at boot
  service:
    name: filebeat
    enabled: no
    state: stopped
  when: not filebeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
